# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CodableMapping' do
    
    #use_frameworks!
    
    pod 'SwiftDate'
    pod 'CodableExtensions'
    
    
end
