# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TrialJTAppleCalendarView' do
    
    use_frameworks!
    
    pod 'JTAppleCalendar', '~> 7.0'
    pod 'NibDesignable', :git => 'https://github.com/wei2lee/NibDesignable.git'
    
    
end
