# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
use_frameworks!

target 'RealmProject' do
    
    pod 'RealmSwift'

    target 'RealmProjectTests' do
        inherit! :search_paths
        pod 'RealmSwift'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

