# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TrialCalendarLib' do
    
    use_frameworks!
    
    pod 'CalendarLib', :git => 'https://github.com/wei2lee/Calendar.git'
    pod 'NibDesignable', :git => 'https://github.com/wei2lee/NibDesignable.git'
    
    
end
